images:
  api:
    repository: ghcr.io/icipe-official/api
    tag: 003dc970
  dbMigrations:
    repository: ghcr.io/icipe-official/db-migrations
    tag: latest
  help:
    repository: ghcr.io/icipe-official/help
    tag: 52fb5ebd
  ingestionapi:
    repository: ghcr.io/icipe-official/ingestionapi
    tag: 003dc970
  tileserver:
    repository: ghcr.io/icipe-official/tileserver
    tag: f331f113
  ui:
    repository: ghcr.io/icipe-official/ui
    tag: c8661e29
  umami:
    repository: ghcr.io/icipe-official/umami
    tag: latest
  nginx:
    tag: eb6a603f
